title: Echoes
cloudinary_cloud_name: dblfokmtd
baseurl: ""
url: "https://evoiu.ro"

permalink: /blog/:slug/

collections:
  galleries:
    output: true
    permalink: /galleries/:name/

defaults:
  - scope: { path: "", type: posts }
    values: { layout: post }
  - scope: { path: "", type: galleries }
    values: { layout: gallery }

exclude:
  - .claude
  - .vscode
